import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navber from "./component/navber";
import Navbar from './component/navber';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Make sure to import the Navbar component

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <div>
          <Navbar /> {/* Place the Navbar here */}
          <main>{children}</main> {/* Wrap children in a main tag */}
        </div>
      </body>
    </html>
  );
}
